name: llm_das
channels:
  - defaults
dependencies:
  - python=3.10.19
  - pip=25.3
  - setuptools=80.9.0
  - wheel=0.45.1
  - numpy=1.26.4
  - pandas=2.3.3
  - scipy=1.15.3
  - scikit-learn=1.7.2
  - requests=2.32.5
  - tqdm=4.67.1
  - matplotlib-base=3.10.8
  - pip:
      - pyod==2.0.6
      - torch==2.9.1
      - fsspec==2026.1.0
      - openai==1.109.1
